# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
compiler: gcc
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake

after_success:
  - Rscript -e 'covr::codecov()'