# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

dist: bionic

warnings_are_errors: false

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gfortran-7

env:
  global:
    - MAKEFLAGS="-j 2"
    - COMPILER=g++-7
    - CC=gcc-7
    - CXX=g++-7
    - CXX17=g++-7 -std=c++17 -fPIC

r_packages:
  - covr
  - devtools

r_github_packages: michbur/tidysq

before_install:
  - mkdir -p ~/.R && touch ~/.R/Makevars
  - VER=-7
  - echo "CC=gcc${VER}"    >> ~/.R/Makevars
  - echo "CXX=g++${VER}"   >> ~/.R/Makevars
  - echo "CXX1X=g++${VER}" >> ~/.R/Makevars
  - echo "CXX17=g++-7 -std=c++17 -fPIC" >> ~/.R/Makevars
  - echo "FC=gfortran${VER}"       >> ~/.R/Makevars
  - echo "F77=gfortran${VER}"      >> ~/.R/Makevars
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

after_success:
  - echo "USE_CXX17 = yes" >> ~/.R/.Renviron
  - echo "CXX17=g++-7 -std=c++17 -fPIC" >> ~/.R/.Renviron
  - echo "CC=gcc${VER}"    >> ~/.R/.Renviron
  - echo "CXX=g++${VER}"   >> ~/.R/.Renviron
  - echo "CXX1X=g++${VER}" >> ~/.R/.Renviron
  - Rscript -e 'covr::codecov(quiet=FALSE)'
  