# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
compiler: gcc
cache: packages
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

r_packages:
  - covr
  - devtools
  
r_github_packages: michbur/tidysq

before_install:
  - sudo mkdir -p ~/.R
  - echo "CXX17=g++-7 -std=c++17 -fPIC" >> ~/.R/Makevars
      
script:
  # Link gcc-7 and g++-7 to their standard commands
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'
  