# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

dist: bionic

warnings_are_errors: false

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gfortran-7

env:
  global:
    - MAKEFLAGS="-j 2"
    - COMPILER=g++-7
    - CC=gcc-7
    - CXX=g++-7
    - CXX17=g++-7 -std=c++17 -fPIC

r_packages:
  - covr
  - devtools

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'
  